version: '2'

services:
### PHP-FPM Container #######################################

    php-fpm:
        container_name: php-fpm
        build:
            context: ./php-fpm
        volumes_from:
            - volumes_source
        expose:
            - "9000"

### Nginx Server Container ##################################
    nginx:
        container_name: nginx
        build:
            context: ./openresty
            args:
                - PHP_UPSTREAM=php-fpm
        volumes:
            - ./openresty/nginx/logs:/opt/openresty/nginx/logs
        volumes_from:
            - volumes_source
        ports:
            - "80:80"
            - "443:443"
        links:
            - php-fpm
### MariaDB Container #######################################

    mariadb:
        container_name: mariadb
        build: ./mariadb
        volumes_from:
            - volumes_data
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: muchrm
            MYSQL_ROOT_PASSWORD: 1vRUtES5ydvvDz)P&
### Application Code Container ######################

    volumes_source:
        image: tianon/true
        volumes:
            - ./workspace/web:/var/www/html
### Databases Data Container ################################

    volumes_data:
        image: tianon/true
        volumes:
            - ./volumes/mysql:/var/lib/mysql
